"""
delete_reconstructed_posts.py

Deletes every post whose post.json has tags including "reconstructed"
(the tag reconstruct_post_json.py applies to posts it rebuilt from rendered
HTML after their original post.json/markdown source was gone). Dry-run by
default.

Run from repo root:
    python delete_reconstructed_posts.py            # dry-run, lists targets
    python delete_reconstructed_posts.py --delete    # actually git rm them
"""
import argparse
import json
import subprocess
from pathlib import Path

DOCS_DIR = Path("./docs")
EXCLUDE_DIRS = {
    "static", "tag", "author", "page",
    "contact", "about", "privacy-policy", "terms-of-service",
    "dmca", "ai-content-policy",
}
TARGET_TAG = "reconstructed"


def find_reconstructed_posts():
    targets = []
    for post_dir in DOCS_DIR.iterdir():
        if not post_dir.is_dir() or post_dir.name in EXCLUDE_DIRS:
            continue
        pj = post_dir / "post.json"
        if not pj.exists():
            continue
        try:
            data = json.loads(pj.read_text(encoding="utf-8"))
        except Exception:
            continue
        tags = [t.lower() for t in data.get("tags", [])]
        if TARGET_TAG in tags:
            targets.append({
                "slug": post_dir.name,
                "title": data.get("title", ""),
                "word_count": len(data.get("content", "").split()),
            })
    return targets


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--delete", action="store_true",
                        help="Actually git rm (default: dry-run)")
    args = parser.parse_args()

    targets = find_reconstructed_posts()

    print(f"{'[DRY RUN] Would delete' if not args.delete else 'Deleting'}: {len(targets)} reconstructed posts")
    for t in sorted(targets, key=lambda x: -x["word_count"]):
        print(
            f"  docs/{t['slug']}/  ({t['word_count']} words)  — {t['title']}")

    with open("remove_reconstructed_posts.sh", "w") as f:
        f.write("#!/usr/bin/env bash\n")
        f.write("# Generated by delete_reconstructed_posts.py\n")
        f.write("set -euo pipefail\n\n")
        for t in targets:
            f.write(f"git rm -r \"docs/{t['slug']}\"\n")
    print("\nWrote remove_reconstructed_posts.sh")

    if args.delete:
        for t in targets:
            subprocess.run(
                ["git", "rm", "-r", f"docs/{t['slug']}"], check=True)
        print(
            f"\nRan git rm on {len(targets)} posts. Review `git status`, then commit.")


if __name__ == "__main__":
    main()
