#!/usr/bin/env bash
# Generated by adsense_compliance_audit.py --delete-improve
set -euo pipefail

git rm -r "docs/ai-tools-for-african-devs-what-actually-works-now"  # ['below_target_length: 1734 < 1800']
git rm -r "docs/3-side-gigs-developers-use-for-12kmo-in-2026"  # ['no_code_in_technical_post']
git rm -r "docs/handoff-latency-kills-systems-60-fix-is-free"  # ['no_code_in_technical_post']
git rm -r "docs/world-models-wont-save-your-backend"  # ['no_code_in_technical_post']
git rm -r "docs/compound-nairobi-6-dev-income-streams-2026"  # ['no_code_in_technical_post']
git rm -r "docs/api-attacks-rise-300-in-2026-whats-breaking-first"  # ['below_target_length: 1705 < 1800']
git rm -r "docs/tech-salaries-2026-what-corrected-what-grew"  # ['no_code_in_technical_post']
git rm -r "docs/vc-insights"  # ['generic_or_missing_meta_description']
git rm -r "docs/handle-starlink-4g-fallbacks-in-fastapi-0115"  # ['below_target_length: 1713 < 1800']
git rm -r "docs/ship-production-grade-tools-in-90-minutes-with-the"  # ['below_target_length: 1221 < 1800']
