#!/usr/bin/env bash
# Generated by delete_reconstructed_posts.py
set -euo pipefail

git rm -r "docs/solid-in-action"
git rm -r "docs/on-call-engineer-survival"
git rm -r "docs/prompt-engineering"
git rm -r "docs/13-ways-developers-can-build-real-influence-at-wor"
git rm -r "docs/pass-remote-tech-interviews-without-leetcode"
git rm -r "docs/sre-fixing-what-breaks-silent"
git rm -r "docs/solid-vs-anti-patterns-in-real-projects"
git rm -r "docs/ai-solo-saas-build-vs-buy-agents-in-2026"
git rm -r "docs/your-data"
git rm -r "docs/debugging-mindset-finally-explained-why-90-of-bugs"
git rm -r "docs/react-server-components-fail-when-hydration-skips-"
git rm -r "docs/run-ai-saas-solo-in-2026"
