"""
adsense_fixes/consent_gate.py  (UPDATED)
==========================================
Generates a GDPR-compliant consent-gated AdSense loader script.

CHANGES FROM v1
---------------
The original v1 had one critical ordering bug (Issue H7):
  The AdSense script tag loaded BEFORE the consent default was set for
  some script execution orders.  This is now fixed by using a single
  inline block for both the dataLayer init and the consent default,
  ensuring they execute synchronously before any external script tag.

A second new fix addresses EU/EEA region-scoping:
  Consent Mode v2 defaults should be scoped to EU/EEA/UK only.
  Setting them globally (as v1 did) caused analytics data loss for
  non-EU visitors even when they never saw the banner.  The region
  parameter is now included on the default call.

WHAT THIS MODULE DOES
---------------------
1. Sets default consent to 'denied' for EU/UK visitors only (region-scoped)
2. Loads gtag.js after the consent default is established
3. Restores prior consent for returning visitors (no banner re-shown)
4. After accept/decline: fires all 6 Consent Mode v2 signals atomically

HOW TO INTEGRATE
----------------
Replace the current global_meta_tags AdSense/GA4 snippet in seo_optimizer.py
with generate_head_snippet(ga_id, adsense_id).

In static_site_generator.py:
    from adsense_fixes.consent_gate import generate_head_snippet
    consent_html = generate_head_snippet(
        ga_id=config.get('google_analytics_id'),
        adsense_id=config.get('google_adsense_id'),
    )
    # Inject consent_html as the FIRST content inside <head>
"""


def generate_head_snippet(ga_id: str, adsense_id: str) -> str:
    """
    Generate the complete <head> analytics + AdSense snippet with
    Consent Mode v2 correctly configured and region-scoped.

    Parameters
    ----------
    ga_id : str
        Google Analytics 4 measurement ID, e.g. 'G-DST4PJYK6V'
    adsense_id : str
        AdSense publisher ID, e.g. 'ca-pub-4477679588953789'

    Returns
    -------
    str
        HTML string to embed as the FIRST thing inside <head>, before
        any other <script> or <link> tags.  Ordering is critical.
    """
    if not ga_id or not adsense_id:
        return "<!-- consent_gate: ga_id or adsense_id missing -->"

    return f"""<!-- ═══════════════════════════════════════════════════════════════════
     Google Consent Mode v2 + GA4 + AdSense
     Generated by adsense_fixes/consent_gate.py
     CRITICAL: This block MUST be the first script in <head>.
     Moving it after any gtag.js load breaks consent mode.
     ═══════════════════════════════════════════════════════════════════ -->
<script>
// ── Step 1: dataLayer + gtag function ───────────────────────────────────────
// Must execute synchronously before any external script tag.
window.dataLayer = window.dataLayer || [];
function gtag(){{dataLayer.push(arguments);}}

// ── Step 2: Set DEFAULT consent to 'denied' — EU/EEA/UK ONLY ────────────────
// Using the 'region' parameter avoids analytics data loss for non-EU visitors.
// Non-EU users are served personalised ads without waiting for a banner.
gtag('consent', 'default', {{
  'region': ['AT','BE','BG','CY','CZ','DE','DK','EE','ES','FI','FR','GB',
             'GR','HR','HU','IE','IS','IT','LI','LT','LU','LV','MT','NL',
             'NO','PL','PT','RO','SE','SI','SK'],
  'ad_storage':              'denied',
  'ad_user_data':            'denied',
  'ad_personalization':      'denied',
  'analytics_storage':       'denied',
  'functionality_storage':   'denied',
  'personalization_storage': 'denied',
  'security_storage':        'granted',
  'wait_for_update':         500,
}});

// ── Step 3: Restore consent for returning EU/UK visitors ────────────────────
// Prevents the banner from showing again once a user has made their choice.
// Reads from a first-party cookie set by consent.js accept() / decline().
(function() {{
  var CONSENT_KEY = 'cookie_consent_v1';
  function getCookie(name) {{
    var escaped = name.replace(/([.*+?^=!:${{}}()|[\\]\\\\\/])/g, '\\\\$1');
    var m = document.cookie.match(new RegExp('(?:^|;)\\\\s*' + escaped + '=([^;]*)'));
    return m ? decodeURIComponent(m[1]) : null;
  }}
  var existing = getCookie(CONSENT_KEY);
  if (existing === 'accepted') {{
    gtag('consent', 'update', {{
      'ad_storage':              'granted',
      'ad_user_data':            'granted',
      'ad_personalization':      'granted',
      'analytics_storage':       'granted',
      'functionality_storage':   'granted',
      'personalization_storage': 'granted',
    }});
  }}
  // 'declined' → keep all denied (Step 2 defaults already cover this)
}})();
</script>

<!-- ── Step 4: Load gtag.js ──────────────────────────────────────────────── -->
<script async src="https://www.googletagmanager.com/gtag/js?id={ga_id}"></script>
<script>
  gtag('js', new Date());
  gtag('config', '{ga_id}', {{
    'send_page_view': true,
    'anonymize_ip': true,
    'cookie_flags': 'SameSite=None;Secure',
  }});
</script>

<!-- ── Step 5: Load AdSense — auto-ads, consent-controlled ─────────────── -->
<!-- Personalisation is governed by the consent state set above.          -->
<!-- Do NOT add this tag again elsewhere on the page.                     -->
<script async
  src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client={adsense_id}"
  crossorigin="anonymous">
</script>
"""


def generate_consent_update_js() -> str:
    """
    Returns the JavaScript snippet to inject into consent.js that fires
    all six Consent Mode v2 signals atomically when a user accepts/declines.

    This replaces the minimal 4-signal update in the original consent.js.

    Usage in consent.js:
        // Replace the existing updateConsent(granted) function with this.
    """
    return """\
// ── Consent Mode v2 atomic update ────────────────────────────────────────────
// Call from accept() and decline() in consent.js.
// ALL six signals must be updated in a single gtag() call to prevent a
// race condition where the AdSense script reads partial consent state.
function updateConsentV2(granted) {
  if (typeof gtag !== 'function') {
    // gtag not loaded yet (very fast user) — push directly to dataLayer
    window.dataLayer = window.dataLayer || [];
    window.dataLayer.push(function() {
      updateConsentV2(granted);
    });
    return;
  }
  var state = granted ? 'granted' : 'denied';
  gtag('consent', 'update', {
    'ad_storage':              state,
    'ad_user_data':            state,
    'ad_personalization':      state,
    'analytics_storage':       state,
    'functionality_storage':   state,
    'personalization_storage': state,
  });
  // Push a consent_update event so GTM/GA4 can track consent rates.
  window.dataLayer.push({
    'event':           'consent_update',
    'consent_granted': granted,
    'consent_method':  'banner',
  });
}
"""
