"""
adsense_fixes/consent_gate.py
===============================
Generates a GDPR-compliant consent-gated AdSense loader script.

WHY THIS EXISTS
---------------
Issue H7 from the audit:
  The AdSense script loads unconditionally on every page.
  For EU/UK visitors, personalised ads must not load before explicit
  consent is given. The current implementation fires `gtag consent update`
  AFTER the AdSense script has already loaded, which is non-compliant.

This module generates a replacement snippet for the <head> that:
  1. Sets default consent state to 'denied' for all ad/analytics storage.
  2. Loads the Google tag (gtag.js) with consent mode v2 defaults.
  3. After the consent banner fires accept/decline:
     - Accepted → grants ad_storage + analytics_storage → AdSense loads
     - Declined → keeps denied → AdSense does not personalise
  4. Returning visitors who already consented have ads load normally
     (no banner re-shown; consent restored from cookie on page load).

HOW TO INTEGRATE
----------------
Replace the current `global_meta_tags` AdSense/GA4 snippet in
`seo_optimizer.py` with the output of `generate_head_snippet(ga_id, adsense_id)`.

Or call from static_site_generator.py:
    from adsense_fixes.consent_gate import generate_head_snippet
    consent_snippet = generate_head_snippet(
        ga_id=config.get('google_analytics_id'),
        adsense_id=config.get('google_adsense_id'),
    )
    # Pass consent_snippet as a template variable and render it in <head>.
"""


def generate_head_snippet(ga_id: str, adsense_id: str) -> str:
    """
    Generate the complete <head> analytics + AdSense snippet with
    Consent Mode v2 correctly configured.

    Parameters
    ----------
    ga_id : str
        Google Analytics 4 measurement ID, e.g. 'G-DST4PJYK6V'
    adsense_id : str
        AdSense publisher ID, e.g. 'ca-pub-4477679588953789'

    Returns
    -------
    str
        HTML string to embed in <head>, before </head>.
    """
    if not ga_id or not adsense_id:
        return "<!-- consent_gate: ga_id or adsense_id missing -->"

    return f"""<!-- Google Consent Mode v2 + Analytics + AdSense (GDPR compliant) -->
<!-- Generated by adsense_fixes/consent_gate.py -->
<script>
// ── Step 1: Define gtag and set DEFAULT consent to 'denied' ──────────────────
// This must execute BEFORE the gtag.js script tag loads.
// EU/UK users will have denied consent until they interact with the banner.
// Non-EU users are unaffected (Google does not apply consent mode globally
// unless the region is EU/EEA/UK).
window.dataLayer = window.dataLayer || [];
function gtag(){{dataLayer.push(arguments);}}

gtag('consent', 'default', {{
  'ad_storage':              'denied',
  'ad_user_data':            'denied',
  'ad_personalization':      'denied',
  'analytics_storage':       'denied',
  'functionality_storage':   'denied',
  'personalization_storage': 'denied',
  'security_storage':        'granted',  // always allowed (session security)
  'wait_for_update':         500,        // ms to wait for consent update before firing
}});

// ── Step 2: Restore consent for returning visitors ───────────────────────────
// If they already accepted or declined, honour it immediately so ads load
// without waiting for the banner (banner won't show for returning visitors).
(function() {{
  var CONSENT_KEY = 'cookie_consent_v1';
  function getCookie(name) {{
    var m = document.cookie.match(
      new RegExp('(?:^|;)\\\\s*' + name.replace(/([.*+?^=!:${{}}()|[\\]\\\\\/])/g, '\\\\$1') + '=([^;]*)'));
    return m ? decodeURIComponent(m[1]) : null;
  }}
  var existing = getCookie(CONSENT_KEY);
  if (existing === 'accepted') {{
    gtag('consent', 'update', {{
      'ad_storage':              'granted',
      'ad_user_data':            'granted',
      'ad_personalization':      'granted',
      'analytics_storage':       'granted',
      'functionality_storage':   'granted',
      'personalization_storage': 'granted',
    }});
  }}
  // If 'declined', keep everything denied (the default above already handles this).
}})();
</script>

<!-- ── Step 3: Load gtag.js ─────────────────────────────────────────────── -->
<script async src="https://www.googletagmanager.com/gtag/js?id={ga_id}"></script>
<script>
  gtag('js', new Date());
  gtag('config', '{ga_id}', {{
    'send_page_view': true,
    'anonymize_ip': true,
  }});
</script>

<!-- ── Step 4: Load AdSense script ──────────────────────────────────────── -->
<!-- AdSense auto-ads. Personalisation is controlled by consent state above. -->
<script async
  src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client={adsense_id}"
  crossorigin="anonymous">
</script>
"""


def generate_consent_update_js() -> str:
    """
    Returns a JavaScript snippet to inject into consent.js that properly
    updates Consent Mode v2 when the user accepts or declines.

    This replaces the existing `updateConsent(granted)` function in consent.js
    with one that fires all Consent Mode v2 signals.
    """
    return """
// ── Consent Mode v2 update (replaces the minimal gtag update) ────────────────
// Call this from accept() and decline() in consent.js.
function updateConsentV2(granted) {
  if (typeof gtag !== 'function') return;
  var state = granted ? 'granted' : 'denied';
  gtag('consent', 'update', {
    'ad_storage':              state,
    'ad_user_data':            state,
    'ad_personalization':      state,
    'analytics_storage':       state,
    'functionality_storage':   state,
    'personalization_storage': state,
  });
  // Push a consent_update event to dataLayer for GTM/GA4 reporting
  window.dataLayer = window.dataLayer || [];
  window.dataLayer.push({
    'event':           'consent_update',
    'consent_granted': granted,
  });
}
"""
