"""
adsense_fixes/schema_validator.py
====================================
Validates and enriches structured data (JSON-LD schema) for AdSense
and Google Search readiness.

WHY THIS EXISTS
---------------
AdSense Site Readiness Guide (§7 Automated Blog Specific Concerns):
  "Schema markup / structured data. Implement Article, BlogPosting,
   or FAQPage schema on posts. This helps Google understand content
   and improves crawl quality."

Google's Rich Results Test checks for:
  - Required properties on Article schema
  - Valid datePublished / dateModified ISO 8601 format
  - Author entity linking to a known person page
  - Publisher with logo
  - Image with explicit dimensions, in a SUPPORTED FORMAT
  - BreadcrumbList on every post

FIX (found in review, 2026)
----------------------------
enrich_article_schema() was hardcoding the OG image URL to the legacy
SVG card generated by image_optimizer.py's generate_og_card(). The
workflow's separate scripts/generate_og_images.py step generates the
real 1200x630 PNG and correctly patches the <meta property="og:image">
tag in the HTML head to point at it — but the JSON-LD Article `image`
field was never updated to match, so it kept pointing at the .svg.

Confirmed live on the deployed site (docs/47-ai-code-debt-in-2026/index.html):
  <meta property="og:image" content=".../47-ai-code-debt-in-2026.png">   (correct)
  "image": {"url": ".../47-ai-code-debt-in-2026.svg", ...}                (JSON-LD — wrong)

SVG is NOT a supported format for the `image` property of Article /
BlogPosting structured data per Google's Rich Results requirements
(JPEG/PNG/WebP/GIF only). This silently disqualified every post on the
site from Article rich-result image eligibility in Search/Discover —
nothing "errors," it just never shows up, which is worse to debug.

This revision:
  1. Points the JSON-LD `image.url` at the real .png instead of .svg.
  2. Accepts an optional `docs_dir` so it can verify the PNG actually
     exists on disk before citing it — if the PNG generation step ever
     fails for a given post, this now omits the `image` field entirely
     rather than silently citing an unsupported/nonexistent format.
  3. validate_article_schema() now checks the image URL's file
     extension against Google's supported list, so this specific bug
     class gets caught by CI next time instead of shipping silently
     for months.

HOW TO INTEGRATE
----------------
In static_site_generator.py, call validate_article_schema() in
_generate_article_schema() BEFORE returning the HTML string:

    from adsense_fixes.schema_validator import (
        enrich_article_schema,
        validate_article_schema,
    )
    schemas = enrich_article_schema(schemas, post, base_url, config, docs_dir=self.output_dir)
    issues = validate_article_schema(schemas)
    if issues:
        print(f"  ⚠️  Schema issues for {post.slug}: {'; '.join(issues)}")
"""

import json
import re
from pathlib import Path
from typing import Dict, List, Optional


# Required Article properties per schema.org + Google Rich Results spec
_REQUIRED_ARTICLE_PROPS = {
    'headline', 'author', 'datePublished', 'image',
}

_ISO_DATE_RE = re.compile(
    r'^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}(:\d{2})?([+-]\d{2}:\d{2}|Z)?)?$')

# Google Rich Results only accepts these formats for the `image` property.
# SVG is deliberately excluded — see module docstring.
_VALID_IMAGE_EXTS = ('.jpg', '.jpeg', '.png', '.webp', '.gif')


# ── Schema enrichment ──────────────────────────────────────────────────────

def enrich_article_schema(
    schemas: List[Dict],
    post,
    base_url: str,
    config: Dict,
    docs_dir: Optional[Path] = None,
) -> List[Dict]:
    """
    Take the existing schemas list (output of _generate_article_schema) and
    add / fix missing required properties.

    Parameters
    ----------
    docs_dir : Path, optional
        If provided, the on-disk output directory is checked to confirm
        the expected PNG OG image actually exists before the JSON-LD
        `image` field is pointed at it. Without this, callers get the
        old best-effort behaviour (URL is built and trusted).

    Mutations applied:
      1. Adds/fixes `image` object to point at the real PNG OG card
         (not the legacy, unsupported-format SVG) with explicit dimensions
      2. Adds publisher logo to Article
      3. Normalises datePublished and dateModified to YYYY-MM-DD format
      4. Ensures inLanguage is present
      5. Adds mainEntityOfPage if not already present
    """
    base = base_url.rstrip('/')
    slug = getattr(post, 'slug', '')
    png_rel_path = f"static/og/{slug}.png"
    og_image_url = f"{base}/{png_rel_path}"

    image_available = True
    if docs_dir is not None:
        local_png = Path(docs_dir) / png_rel_path
        if not local_png.exists():
            image_available = False
            print(
                f"  ⚠️  Schema: expected OG PNG missing for '{slug}' "
                f"({local_png}) — Article image schema will be left as-is "
                f"rather than pointing at the unsupported .svg fallback."
            )

    for schema in schemas:
        if schema.get('@type') not in ('Article', 'BlogPosting'):
            continue

        # 1. Image with dimensions — only overwrite if missing, or if the
        #    current value is in an unsupported format (e.g. the legacy .svg).
        current_image = schema.get('image')
        needs_fix = (
            current_image is None
            or (
                isinstance(current_image, dict)
                and not str(current_image.get('url', '')).lower().endswith(_VALID_IMAGE_EXTS)
            )
            or (
                isinstance(current_image, str)
                and not current_image.lower().endswith(_VALID_IMAGE_EXTS)
            )
        )
        if needs_fix and image_available:
            schema['image'] = {
                '@type': 'ImageObject',
                'url': og_image_url,
                'width': 1200,
                'height': 630,
                'caption': getattr(post, 'title', ''),
            }

        # 2. Publisher with logo
        if 'publisher' not in schema:
            schema['publisher'] = _build_publisher(base, config)
        elif 'logo' not in schema.get('publisher', {}):
            schema['publisher']['logo'] = _build_logo(base)

        # 3. Normalise dates
        for date_field in ('datePublished', 'dateModified'):
            raw = schema.get(date_field, '')
            normalised = _normalise_date(raw)
            if normalised:
                schema[date_field] = normalised

        # 4. Ensure inLanguage
        schema.setdefault('inLanguage', 'en-US')

        # 5. mainEntityOfPage
        if 'mainEntityOfPage' not in schema:
            schema['mainEntityOfPage'] = {
                '@type': 'WebPage',
                '@id': f"{base}/{slug}/",
            }

    return schemas


def _build_publisher(base_url: str, config: Dict) -> Dict:
    site_name = config.get('site_name', 'Tech Blog')
    return {
        '@type': 'Organization',
        'name': site_name,
        'url': base_url,
        'logo': _build_logo(base_url),
        'sameAs': [
            'https://twitter.com/KubaiKevin',
            'https://www.linkedin.com/in/kevin-kubai-22b61b37/',
        ],
    }


def _build_logo(base_url: str) -> Dict:
    # NOTE: this file's existence is not verified the way the OG image now
    # is. If generate_icons.py hasn't been run for this deployment, this
    # 404s in exactly the same way the OG image did — worth wiring the same
    # on-disk check through here if that ever becomes a live issue.
    return {
        '@type': 'ImageObject',
        'url': f"{base_url}/static/icons/icon-512x512.png",
        'width': 512,
        'height': 512,
    }


def _normalise_date(raw: str) -> Optional[str]:
    """
    Normalise an ISO date string to YYYY-MM-DD format.
    Returns None if the input cannot be parsed.
    """
    if not raw:
        return None
    # Already YYYY-MM-DD
    if re.match(r'^\d{4}-\d{2}-\d{2}$', raw):
        return raw
    # Strip time component
    if 'T' in raw:
        return raw.split('T')[0]
    return None


# ── Schema validation ──────────────────────────────────────────────────────

def validate_article_schema(schemas: List[Dict]) -> List[str]:
    """
    Validate the schemas list for required properties.
    Returns a list of issue strings (empty list = valid).

    This is a lightweight pre-publish check — not a full JSON-LD validator.
    Use Google's Rich Results Test for definitive validation before submission.
    """
    issues = []

    for schema in schemas:
        schema_type = schema.get('@type', '')

        if schema_type in ('Article', 'BlogPosting'):
            # Check required properties
            for prop in _REQUIRED_ARTICLE_PROPS:
                if prop not in schema:
                    issues.append(
                        f"Article schema missing required property: '{prop}'"
                    )

            # Validate date formats
            for date_field in ('datePublished', 'dateModified'):
                date_val = schema.get(date_field, '')
                if date_val and not _ISO_DATE_RE.match(str(date_val)):
                    issues.append(
                        f"'{date_field}' value '{date_val}' is not valid ISO 8601."
                    )

            # Validate author structure
            author = schema.get('author', {})
            if isinstance(author, dict):
                if 'name' not in author:
                    issues.append("Article author is missing 'name' property.")
                if '@type' not in author:
                    issues.append(
                        "Article author is missing '@type' (should be 'Person')."
                    )
            elif not author:
                issues.append("Article 'author' is empty.")

            # Validate image — including format, which is the bug this
            # revision fixes. A URL that "exists" but isn't in
            # _VALID_IMAGE_EXTS is treated as a validation failure, not
            # a pass, because Google Rich Results silently ignores it.
            image = schema.get('image', {})
            if isinstance(image, dict):
                url = image.get('url', '')
                if not url:
                    issues.append("Article image is missing 'url'.")
                elif not url.lower().endswith(_VALID_IMAGE_EXTS):
                    issues.append(
                        f"Article image '{url}' is not a Rich-Results-supported "
                        f"format ({', '.join(_VALID_IMAGE_EXTS)}) — SVG and other "
                        f"vector/unsupported formats are silently ignored by Google."
                    )
            elif isinstance(image, str):
                if not image.lower().endswith(_VALID_IMAGE_EXTS):
                    issues.append(
                        f"Article image string '{image}' is not a supported format "
                        f"({', '.join(_VALID_IMAGE_EXTS)})."
                    )
            elif not image:
                issues.append(
                    "Article schema missing 'image' — required for Rich Results.")

            # Headline length
            headline = schema.get('headline', '')
            if headline and len(headline) > 110:
                issues.append(
                    f"Article headline is {len(headline)} chars — Google recommends < 110."
                )

        elif schema_type == 'BreadcrumbList':
            items = schema.get('itemListElement', [])
            if not items:
                issues.append("BreadcrumbList has no itemListElement entries.")
            for item in items:
                if 'item' not in item or 'name' not in item:
                    issues.append(
                        "BreadcrumbList item is missing 'name' or 'item' URL."
                    )

    return issues


# ── FAQ schema builder ──────────────────────────────────────────────────────

def extract_and_build_faq_schema(content: str, base_url: str, slug: str) -> Optional[str]:
    """
    Extract FAQ questions and answers from the markdown content and
    return a JSON-LD FAQPage schema string, or None if no FAQ section found.

    The FAQ section must use ## Frequently Asked Questions heading.
    Questions must be ### subheadings.  Answers are the following paragraphs.
    """
    # Find FAQ section
    faq_pattern = re.compile(
        r'##\s+(?:Frequently\s+Asked\s+Questions|FAQ)\s*\n([\s\S]+?)(?=\n##\s|\Z)',
        re.IGNORECASE,
    )
    faq_match = faq_pattern.search(content)
    if not faq_match:
        return None

    faq_body = faq_match.group(1)

    # Extract Q&A pairs (### Question \n answer paragraph)
    qa_pattern = re.compile(
        r'###\s+(.+?)\n([\s\S]+?)(?=\n###\s|\Z)',
        re.IGNORECASE,
    )

    entries = []
    for qa_match in qa_pattern.finditer(faq_body):
        question = qa_match.group(1).strip().rstrip('?') + '?'
        answer_raw = qa_match.group(2).strip()
        # Strip markdown from answer
        answer = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', answer_raw)
        answer = re.sub(r'[*_`#]', '', answer)
        answer = re.sub(r'\s+', ' ', answer).strip()

        if question and answer and len(answer) > 20:
            entries.append({
                '@type': 'Question',
                'name': question,
                'acceptedAnswer': {
                    '@type': 'Answer',
                    'text': answer[:2000],   # Google recommends < 2000 chars
                },
            })

    if not entries:
        return None

    schema = {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        '@id': f"{base_url}/{slug}/#faq",
        'mainEntity': entries,
    }

    try:
        return json.dumps(schema, indent=2, ensure_ascii=False)
    except Exception:
        return None